language: objective-c
osx_image: xcode12
env:
  - DESTINATION="platform=iOS\ Simulator,name=iPhone\ 8"
  - DESTINATION="platform=iOS\ Simulator,name=iPhone\ 11"
  - DESTINATION="platform=iOS\ Simulator,name=iPad\ (7th\ generation)"
script:
  - CODE_SIGNING_REQUIRED=NO xcodebuild clean test -sdk iphonesimulator -project NZSLDict.xcodeproj -scheme NZSLDictTests  -destination $DESTINATION
